### ISSUE TITLE
OpenLayers.control.Profil in OpenLayers 2?

### ISSUE THREAD

**Issue by vsevjednom-cz** [Viglino/OpenLayers-ext#2]
Hi,
I'm very new in work with OpenLayers. I'm using OpenLayers 2 and I don't know why. Your extension is amazing!!! It works nice. But I can't to do only one thing: I need to create this: https://viglino.github.io/ol-ext/examples/control/map.control.profil.html in OpenLayers 2 and with your extension OpenLayers-ext. Is it possible? It's very difficult to update my scripts from OpenLayers 2 to OpenLayers 3. This is the reason why I need elevation profile in OpenLayers 2.

**Comment by Viglino** [comment]
Sorry, this repo is deprecated an no more maintained.
I recommend to switch to last version of Openlayers.
You can look at [the Profil control code](https://github.com/Viglino/ol-ext/blob/master/src/control/Profile.js) to handle the drawing of a profil on a canvas to integrate it in your code.

**Comment by vsevjednom-cz** [comment]
Thank you for your reply! Do you know simply instructions for switch from version 2 to newer? Because there are too much problems with it. For example: I'm using OpenLayers.Layer.Text and loading text with photos from txt file (lat lon title description iconSize icon). New versions works differently, I understand but I can't find some replacement for this :(. This is the reason why I must stay with old version. Can you help me? Pleeaase.

**Comment by Viglino** [comment]
Have a look at this example to convert a CSV to GeoJSON: https://viglino.github.io/ol-ext/examples/misc/csv2geojson.html
Then use [ol/format/GeoJSON](https://openlayers.org/en/latest/apidoc/module-ol_format_GeoJSON-GeoJSON.html) to read features and place them in a Vector source (see https://openlayers.org/en/latest/examples/geojson.html).

**Comment by vsevjednom-cz** [comment]
Thanks again! It works but I need to create some little icons (camera for example) and pop up after click. Something what looks like this: http://dev.openlayers.org/releases/OpenLayers-2.13.1/examples/popupMatrix.html

I'm sorry I bother you here. Can you help me last time? I hope I can switch to OL3 after this and use your ol-ext :).

**Comment by Viglino** [comment]
You have to look at Openlayers styles: https://openlayers.org/en/latest/examples/index.html?q=style
ol-ext use fonts to display icons on the map: https://viglino.github.io/ol-ext/examples/style/map.style.font.html 
There is popup overlay in ol-ext

Look at this example with popup and camera: https://viglino.github.io/ol-ext/examples/popup/map.popup.html

**Comment by vsevjednom-cz** [comment]
Amazing! I got it! I'm using ol-ext! Thank you. And last question: I need for every point in map different icon. I'm loading all points and icons from JSON file. There wasn't any problem in OL2 and CSV file. I'm googling and googling many hours but without success :(.

**Comment by Viglino** [comment]
You have to make a style per feature with its own icon.

**Comment by vsevjednom-cz** [comment]
Done! Can I send you some little support amount? :)

**Comment by Viglino** [comment]
Just star the repository 😄
